### ISSUE TITLE
Viewing past activity throws ISE

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#270] opened 2015-12-23 14:59 UTC
Rebecca Nesvet reports: 

Tried to check out my past activity, because if I can see the editors’, I will know if my students are doing their homework. (They usually do, of course, and then much more than assigned, on this project anyhow.) But I got an error message: “500 Internal Server Error. We're sorry, but something went wrong. Please try to refresh the page, if the problem persists feel free to contact us.”

**Comment by saracarl** [comment] 2016-04-14 19:13
couldn't reproduce, not sure what this is referring to.

**Comment by saracarl** [comment] 2017-04-05 22:55
Closing.  (can't reproduce/likely fixed.)

**Closed** 2017-04-05 22:55 UTC
