### ISSUE TITLE
500 error on a subject page

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4034] opened 2024-04-11 21:15 UTC
Getty is getting a 500 error going to this page:
https://fromthepage.com/gri/stendahl-letters-qc/article/32081279

 this is the error:

> F, [2024-04-11T21:13:25.224085 #18042] FATAL -- :   
> ActionView::Template::Error (undefined method `title' for nil:NilClass):
>     19:     -@article.target_article_links.each do |link|
>     20:       li
>     21:         =svg_symbol '#icon-page', class: 'icon'
>     22:         =link_to link.source_article.title, collection_article_show_path(@collection.owner, @collection, link.source_article.id)
>     23:         =="&nbsp;&mdash;&nbsp;#{link.display_text}"
>   
> app/views/article/_article_links.html.slim:22
> app/views/article/_article_links.html.slim:19
> app/views/article/show.html.slim:42
> app/controllers/application_controller.rb:64:in `switch_locale'
>

**Comment by benwbrum** [comment] 2024-04-12 14:08
Duplicate of #3993 -- this should be a higher priority issue, as it is happening frequently.

**Closed by benwbrum** 2024-04-12 14:08 UTC
Labels: customer
