### ISSUE TITLE
breadcrumbs for docset to collection

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2434] opened 2021-03-08 20:35 UTC
If you have access to a collection, we should show it in "breadcrumbs" at the top of a document set listing.

**Comment by saracarl** [comment] 2021-04-28 16:23
Mount Auburn would like this as well.

**Comment by benwbrum** [comment] 2023-08-03 21:21
Duplicate of #1983

**Comment by benwbrum** [comment] 2023-09-11 18:54
Duplicate

**Comment by benwbrum** [comment] 2023-10-16 13:18
Duplicate

**Closed by benwbrum** 2023-10-16 13:18 UTC
Labels: customer
