### ISSUE TITLE
saving a page call process_tex_figures (and shouldn't)

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#521] opened 2017-01-13 19:01 UTC
e.g. 17108 doesn't have any tex figures, but calls the rake task anyway.  Perhaps is table related, since that page has tables?

I, [2017-01-13T18:57:26.868148 #29113]  INFO -- : Started PATCH "/transcribe/save_transcription" for 70.112.51.219 at 2017-01-13 18:57:26 +0000
I, [2017-01-13T18:57:26.871556 #29113]  INFO -- : Processing by TranscribeController#save_transcription as HTML
I, [2017-01-13T18:57:26.871740 #29113]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"+DraE7tl/gG0q32BrXuSyqsb+pV/W9r6eD3ywQTscxY=", "page_id"=>"17108", "page"=>{"status"=>"", "source_text"=>"Estimate of Expenditures for the 13th Light-House District\r\nduring the six months ending December 31st, 1887.\r\n\r\n==Appropriations for Repairs and Incidental Expenses of Light Houses 1888.==\r\n\r\n|Items | Urgent | Not Urgent|\r\n|---------|-------------|------------------|\r\n|1 lightning rod and ground connection for dwelling|25.00||\r\n|1 ground connection for rod on tower|12.50||\r\n|Mirror protection of sliding bluff Estimate forwarded December 13th, 1886||420.00|\r\n||37.50||\r\n\r\n"}, "save"=>""}
I, [2017-01-13T18:57:27.408946 #29113]  INFO -- : TRANSCRIPTION	2017-01-13 18:57:27 +0000
TRANSCRIPTION	User	ID: 4	Email: saracarl@gmail.com	Display Name: Sara Brumfield
TRANSCRIPTION	Collection	ID: 60	Title:Private non trascribed	Owner Email: blm_or_yh_education@blm.gov
TRANSCRIPTION	Work	ID: 273	Title: Vol 705 New Barn 1886
TRANSCRIPTION	Page	ID: 17108	Position: 7	Title:7
TRANSCRIPTION	Source Text:
BEGIN_SOURCE_TEXT
Estimate of Expenditures for the 13th Light-House District
during the six months ending December 31st, 1887.

==Appropriations for Repairs and Incidental Expenses of Light Houses 1888.==

|Items | Urgent | Not Urgent|
|---------|-------------|------------------|
|1 lightning rod and ground connection for dwelling|25.00||
|1 ground connection for rod on tower|12.50||
|Mirror protection of sliding bluff Estimate forwarded December 13th, 1886||420.00|
||37.50||

END_SOURCE_TEXT

I, [2017-01-13T18:57:27.560037 #29113]  INFO -- : TRANSCRIPTION	2017-01-13 18:57:27 +0000	SUCCESS	
I, [2017-01-13T18:57:27.587894 #29113]  INFO -- : /usr/bin/env rake fromthepage:process_tex_figures[17108]  --trace 2>&1 >> /home/fromthepage/deployment/releases/20170112141433/public/images/working/tex/17108/process.log &

**Comment by tbl73** [comment] 2017-02-27 15:59
That call is made in the page save in the transcribe controller, without checking anywhere along the way to see if there are tex figues involved - if you look at line 55 in the transcribe controller, it calls @page.submit_background_processes, which calls TexFigure.submit_background_processes (in line 197 of the page model).  That call (line 29 in the TexFigure model) triggers the rake task.

**Comment by tbl73** [comment] 2017-09-07 19:03
This was a dupe of #705 . Closing.

**Closed by tbl73** 2017-09-07 19:03 UTC
