### ISSUE TITLE
adding transcribers to restricted works should check collection permissions

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#2823] opened 2021-10-21 14:47 UTC
If a transcriber is added to a restricted work on a private collection, we should verify they are collaborators on the collection,  If they aren't, we should add them and tell the project owner in a pop-up.

**Comment by benwbrum** [comment] 2021-12-29 20:09
Duplicate of #2315

**Closed** 2021-12-29 20:09 UTC
