### ISSUE TITLE
crash on upload

### ISSUE THREAD

**Issue by srl295** [benwbrum/fromthepage#266] opened 2015-11-28 22:09 UTC
maybe related to #263 
merged in c998e1ecfd9ea498b1a19f18ce490f6f4f5b9b6c from ui-design

on upload of a large pdf:
```
I, [2015-11-28T14:03:52.300492 #3746]  INFO -- : Processing by DashboardController#new_upload as HTML
I, [2015-11-28T14:03:52.300697 #3746]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"CNEiM4797Shc2VjsmWQhWwPSx+O8PgOFkeDcpuJ2Sa8=", "document_upload"=>{"collection_id"=>"1", "file"=>#<ActionDispatch::Http::UploadedFile:0x007f9862e41c48 @tempfile=#<Tempfile:/var/folders/67/ydtxt4ms3fnbwbgqfmnt7_3r0000gn/T/RackMultipart20151128-3746-48y9eo>, @original_filename="Diary 1911.pdf", @content_type="application/pdf", @headers="Content-Disposition: form-data; name=\"document_upload[file]\"; filename=\"Diary%201911.pdf\"\r\nContent-Type: application/pdf\r\n">}, "button"=>""}
I, [2015-11-28T14:03:56.622998 #3746]  INFO -- :   Rendered system_mailer/new_upload.html.erb within layouts/mailer (6.6ms)
I, [2015-11-28T14:03:56.623411 #3746]  INFO -- : Completed 500 Internal Server Error in 4322ms
F, [2015-11-28T14:03:56.626886 #3746] FATAL -- : 
ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
    53: 
    54: <div style="margin-top:20px; padding-top:20px; border-top:1px solid #D3CFC6">
    55:   View all uploads at the
    56:   <%= link_to 'upload dashboard', { controller: 'admin', action: 'uploads', only_path: false } %>.
    57: </div>
  app/views/system_mailer/new_upload.html.erb:56:in `_app_views_system_mailer_new_upload_html_erb__4367087655033331848_70146263696520'
  app/mailers/system_mailer.rb:20:in `new_upload'
  app/controllers/dashboard_controller.rb:56:in `new_upload'

```

( PS: sorry I have filed more bugs than responded. I will try to get back to responding)

**Comment by benwbrum** [comment] 2015-11-28 22:42
This is dying because the upload-started email can't be sent from your server. Run the two rake tasks to test your server configuration (rake -T | grep fromthepage) and set the mail server hosts appropriately.

**Comment by srl295** [comment] 2015-11-29 06:50
great thx

**Comment by saracarl** [comment] 2016-04-14 19:17
Closing as a duplicate of #280 -- we definitely need to improve this, though!

**Closed by saracarl** 2016-04-14 19:17 UTC
