### ISSUE TITLE
Imported documents show "edited" rather than "transcribed"

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#1040] opened 2018-04-15 13:48 UTC
AL's transcription events are being recorded as page edits, not initial transcriptions.  

(Maybe just remediate by setting the initial edit as version 0 instead of 1?)

Question:  are all IIIF imports / ContentDM imports suffering from the same problem?

**Comment by saracarl** [comment] 2018-04-15 14:01
This may be a IIIF import issue -- UCD shows 2 pages transcribed and 538 edited.

**Comment by jackweinbender** [comment] 2019-09-29 20:10
I'm having some difficulty reproducing this. CDM imports seem to function as intended (as far as I can tell), and I've also added pages to Alabama collections (thinking it could be related to field-based transcription?), but, again, it seems to be working as expected.

**Comment by jackweinbender** [comment] 2019-09-30 16:30
Ben suggested that this may have been solved by another issue and that---unless I have some reason to think that it is still a bug---I should close the issue.

**Closed by jackweinbender** 2019-09-30 16:30 UTC
Labels: bug, contentdm
