### ISSUE TITLE
Page Status Window needs a "completed" entry

### ISSUE THREAD

**Issue by NatWooding** [benwbrum/fromthepage#32] opened 2014-01-16 00:02 UTC
In From the Page, the page status drop down window only has "Incomplete transcription" and "Blank: nothing to transcribe". It needs a "Transcription Complete" entry for use when the transcription is complete after it had earlier been marked incomplete.

E.g., Grinnell S3 Page 8
http://beta.fromthepage.com/display/display_page?page_id=4364

**Comment by saracarl** [comment] 2016-09-08 21:35
Dupe of #276 ; closing and tracking there.  (I actually think we'll get this fixed in the next 6 months...  :)  )

**Closed by saracarl** 2016-09-08 21:35 UTC
