### ISSUE TITLE
login/logout/etc redirects https to http

### ISSUE THREAD

**Issue by srl295** [benwbrum/fromthepage#272] opened 2015-12-23 18:33 UTC
I'm using FTP behind a proxy for SSL reasons. 

Something (devise?) is redirecting from https to http on something like a logout. I can't find it in the FTP code.

**Comment by benwbrum** [comment] 2015-12-23 20:27
I think the code you might be looking for is this: https://github.com/benwbrum/fromthepage/blob/master/app/controllers/application_controller.rb#L183-L189

It gets fired on registration and sign-in, and might also be called on a logout.  Throw `binding.pry` into it and see.

**Comment by srl295** [comment] 2015-12-23 20:31
Actually the issue seems to be one with apache httpd -  https://bugs.ruby-lang.org/issues/10789

**Comment by benwbrum** [comment] 2015-12-23 20:38
Oh!  Interesting.

As far as I know, you're the first person who's running FromThePage on HTTPS

**Comment by saracarl** [comment] 2016-04-14 19:11
@srl295 Did 
RequestHeader set X-Forwarded-Proto "https"
fix this?  (If not, we'll investigate more.)

Thanks!

**Comment by srl295** [comment] 2016-04-16 22:50
Hi! I think so but its not running now. Probably I'll switch to docker as a
main container.

**Comment by saracarl** [comment] 2017-07-26 15:37
we're running fromthepage.com with ssl certs now, and I can't reproduce this.  Possibly what you need is config change #2 on this page:

https://github.com/benwbrum/fromthepage/wiki/Configuring-FromThePage-For-Your-Environment

closing.  please reopen if the problem keeps occurring.

**Closed by saracarl** 2017-07-26 15:37 UTC

**Comment by bencomp** [comment] 2017-11-01 09:19
FYI setting `RequestHeader set X-Forwarded-Proto "https"` worked for me. IIIF URIs start with https, whereas they didn't before.

Note: `https` must be lower-case for it to work, as I had run the reverse proxy with `HTTPS` from the start to no effect.
