### ISSUE TITLE
duplicate upload work

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4353] opened 2024-09-28 16:14 UTC
TN State Archives are seeing duplicate works after uploading:
![duplicates](https://github.com/user-attachments/assets/ad164562-1217-483a-be26-c4c512110ef1)

When I went to find an example, however, there was only one:
![image](https://github.com/user-attachments/assets/57edc852-326b-46e4-b541-75901944ab93)
I'm asking if they deleted the duplicate.

I determined the file was just uploaded once, and had a successful upload processing.  The processing log, however, only shows creating pages for the first 40 pages, which is weird:

[view_processing_log.txt](https://github.com/user-attachments/files/17175432/view_processing_log.txt)

I also unzipped the uploaded file and looked for any duplicate folders; there were none.  

https://fromthepage.com/admin/view_processing_log?id=32026693

~/deployment/releases/20240920211105/public/uploads/document_upload/file/32026693

no deployments during or after -- this release folder is the current one.

**Comment by benwbrum** [comment] 2024-10-02 02:18
We just got some more reproduction steps from Darren at SLQ.
He uploaded this file: [33054-004722.zip](https://github.com/user-attachments/files/17218942/33054-004722.zip)

That resulted in two identical-looking uploaded works:
![Screenshot from 2024-10-01 21-09-39](https://github.com/user-attachments/assets/75349180-f339-45a6-b6d0-4f5335b00827)

If I compare the works (or the first page of each work) in the database, the only differences in attributes are the ones you'd expect if you intentionally ran the ingestor twice:
```
2.7.3 :008 > work1.attributes.to_a - work2.attributes.to_a
 => [["id", 32142103], ["created_on", Tue, 01 Oct 2024 22:43:02.000000000 UTC +00:00], ["slug", "work-33054-004722"], ["featured_page", 34496300], ["next_untranscribed_page_id", 34496300], ["searchable_metadata", "33054-004722\n\n2024-10-01 22:43:02 UTC\n\ntrue\n\n33054-004722"], ["most_recent_deed_created_at", Tue, 01 Oct 2024 22:43:07.000000000 UTC +00:00]] 


2.7.3 :011 > work1.pages.first.attributes.to_a - work2.pages.first.attributes.to_a
 => [["id", 34496300], ["base_image", "/home/fromthepage/deployment/releases/20240920211105/public/images/uploaded/32142103/33054-004722-0001.jpg"], ["work_id", 32142103], ["created_on", Tue, 01 Oct 2024 22:43:04.000000000 UTC +00:00], ["page_version_id", 38603339], ["updated_at", Tue, 01 Oct 2024 22:43:04.000000000 UTC +00:00]] 
```


The [processing log file](https://fromthepage.com/admin/view_processing_log?id=32026957) looks like it's only ingesting a single work:
```
convert_to_work succeeded for 33054-004721
Finished converting files in /tmp/fromthepage_uploads/32026956/33054-004721 to a work
Finished ingest_tree for /tmp/fromthepage_uploads/32026956/33054-004721
ingest_tree considering /tmp/fromthepage_uploads/32026956/33054-004721.zip)
Finished ingest_tree for /tmp/fromthepage_uploads/32026956
Removing /tmp/fromthepage_uploads/32026956
fetching upload with ID=32026956
found document_upload for 
	user=darren, 
	target collection=Colonial Secretary's Correspondence, 
	file=/uploads/document_upload/file/32026956/33054-004721.zip
creating temp directory /tmp/fromthepage_uploads/32026956
copying /home/fromthepage/deployment/releases/20240920211105/public/uploads/document_upload/file/32026956/* to /tmp/fromthepage_uploads/32026956
unzip_tree(/tmp/fromthepage_uploads/32026956)
	unzip_tree considering /tmp/fromthepage_uploads/32026956/33054-004721.zip
Found zipfile /tmp/fromthepage_uploads/32026956/33054-004721.zip
Calling unzip_file(/tmp/fromthepage_uploads/32026956/33054-004721.zip, /tmp/fromthepage_uploads/32026956/33054-004721)
upzip_file(/tmp/fromthepage_uploads/32026956/33054-004721.zip)
	extracting /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.jpg
	extracting /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.jpg
	extracting /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.jpg
	extracting /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.txt
	extracting /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.txt
	extracting /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.txt
unzip_tree(/tmp/fromthepage_uploads/32026956/33054-004721)
	unzip_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.jpg
	unzip_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.txt
	unzip_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.jpg
	unzip_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.txt
	unzip_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.jpg
	unzip_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.txt
unpdf_tree(/tmp/fromthepage_uploads/32026956)
	unpdf_tree considering /tmp/fromthepage_uploads/32026956/33054-004721)
	unpdf_tree Found directory /tmp/fromthepage_uploads/32026956/33054-004721
unpdf_tree(/tmp/fromthepage_uploads/32026956/33054-004721)
	unpdf_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.jpg)
	unpdf_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.txt)
	unpdf_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.jpg)
	unpdf_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.txt)
	unpdf_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.jpg)
	unpdf_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.txt)
	unpdf_tree considering /tmp/fromthepage_uploads/32026956/33054-004721.zip)
convert tiffs from tree(/tmp/fromthepage_uploads/32026956)
	untiff_tree considering /tmp/fromthepage_uploads/32026956/33054-004721)
Found directory /tmp/fromthepage_uploads/32026956/33054-004721
convert tiffs from tree(/tmp/fromthepage_uploads/32026956/33054-004721)
	untiff_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.jpg)
	untiff_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.txt)
	untiff_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.jpg)
	untiff_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.txt)
	untiff_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.jpg)
	untiff_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.txt)
	untiff_tree considering /tmp/fromthepage_uploads/32026956/33054-004721.zip)
compress tree(/tmp/fromthepage_uploads/32026956)
compress_tree handling /tmp/fromthepage_uploads/32026956/33054-004721)
Found directory /tmp/fromthepage_uploads/32026956/33054-004721
compress tree(/tmp/fromthepage_uploads/32026956/33054-004721)
compress_tree handling /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.jpg)
Found image /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.jpg
"Compressed file is now 4632468 at quality 90"
"Compressed file is now 2969567 at quality 80"
"Compressed file is now 2551549 at quality 70"
"Compressed file is now 2019515 at quality 60"
"Compressed file is now 1774802 at quality 50"
compressed.write('/tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.jpg')  { self.quality = 50 }compress_tree handling /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.txt)
compress_tree handling /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.jpg)
Found image /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.jpg
"Compressed file is now 5221849 at quality 90"
"Compressed file is now 3324025 at quality 80"
"Compressed file is now 2840717 at quality 70"
"Compressed file is now 2233365 at quality 60"
"Compressed file is now 1950857 at quality 50"
compressed.write('/tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.jpg')  { self.quality = 50 }compress_tree handling /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.txt)
compress_tree handling /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.jpg)
Found image /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.jpg
"Compressed file is now 4707162 at quality 90"
"Compressed file is now 2930337 at quality 80"
"Compressed file is now 2465263 at quality 70"
"Compressed file is now 1897516 at quality 60"
compressed.write('/tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.jpg')  { self.quality = 60 }compress_tree handling /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.txt)
compress_tree handling /tmp/fromthepage_uploads/32026956/33054-004721.zip)
ingest_tree(/tmp/fromthepage_uploads/32026956)
ingest_tree considering /tmp/fromthepage_uploads/32026956/33054-004721)
Found directory /tmp/fromthepage_uploads/32026956/33054-004721
ingest_tree(/tmp/fromthepage_uploads/32026956/33054-004721)
ingest_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.jpg)
ingest_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.txt)
ingest_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.jpg)
ingest_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.txt)
ingest_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.jpg)
ingest_tree considering /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.txt)
Found 3 image files in /tmp/fromthepage_uploads/32026956/33054-004721 -- converting to a work
convert_to_work creating database record for /tmp/fromthepage_uploads/32026956/33054-004721
	convert_to_work owner = darren
	convert_to_work collection = Colonial Secretary's Correspondence
	convert_to_work default title = 33054-004721
	convert_to_work looking for metadata.yml in /tmp/fromthepage_uploads/32026956/metadata.yml
	convert_to_work no metadata.yml file; using default settings
	convert_to_work loaded metadata.yml values 

	convert_to_work creating /home/fromthepage/deployment/releases/20240920211105/public/images/uploaded/32142102
			cp /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.jpg to /home/fromthepage/deployment/releases/20240920211105/public/images/uploaded/32142102
			cp /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.jpg to /home/fromthepage/deployment/releases/20240920211105/public/images/uploaded/32142102
			cp /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.jpg to /home/fromthepage/deployment/releases/20240920211105/public/images/uploaded/32142102
		convert_to_work created new page
		convert_to_work before Magick call 
		convert_to_work calculating base and height 
		convert_to_work reading raw OCR text from /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0001.txt
		convert_to_work added /home/fromthepage/deployment/releases/20240920211105/public/images/uploaded/32142102/33054-004721-0001.jpg to work as page 33054-004721-0001, id=34496297
		convert_to_work created new page
		convert_to_work before Magick call 
		convert_to_work calculating base and height 
		convert_to_work reading raw OCR text from /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0002.txt
		convert_to_work added /home/fromthepage/deployment/releases/20240920211105/public/images/uploaded/32142102/33054-004721-0002.jpg to work as page 33054-004721-0002, id=34496298
		convert_to_work created new page
		convert_to_work before Magick call 
		convert_to_work calculating base and height 
		convert_to_work reading raw OCR text from /tmp/fromthepage_uploads/32026956/33054-004721/33054-004721-0003.txt
		convert_to_work added /home/fromthepage/deployment/releases/20240920211105/public/images/uploaded/32142102/33054-004721-0003.jpg to work as page 33054-004721-0003, id=34496299
convert_to_work succeeded for 33054-004721
Finished converting files in /tmp/fromthepage_uploads/32026956/33054-004721 to a work
Finished ingest_tree for /tmp/fromthepage_uploads/32026956/33054-004721
ingest_tree considering /tmp/fromthepage_uploads/32026956/33054-004721.zip)
Finished ingest_tree for /tmp/fromthepage_uploads/32026956
Removing /tmp/fromthepage_uploads/32026956
```

**Comment by WillNigel23** [comment] 2024-10-02 16:15
This is likely related to #4271

It should be fixed. But then if they are working on a fork, they should do a server restart for the fix to apply.

I tried this now in our fromthepage prod with the file mentioned above, I did not get duplicates.

**Comment by WillNigel23** [comment] 2024-10-02 16:16
For reference, PR fixing this is #4285

**Comment by WillNigel23** [comment] 2024-10-02 16:21
https://fromthepage.com/wcdejesus/test-duplicate

This is the collection I tried to reproduce it from

**Closed** 2024-10-03 14:18 UTC
Labels: customer
