### ISSUE TITLE
error in metadata description

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#3487] opened 2023-01-28 13:38 UTC
```I, [2023-01-28T13:06:07.139474 #759]  INFO -- :   Rendered shared/_description_tabs.html.slim (Duration: 105.0ms | Allocations: 39170)
I, [2023-01-28T13:06:07.140179 #759]  INFO -- :   Rendered work/describe.html.slim within layouts/application (Duration: 123.8ms | Allocations: 65425)
I, [2023-01-28T13:06:07.141492 #759]  INFO -- : Completed 500  in 144ms (ActiveRecord: 32.3ms | Allocations: 73605)

F, [2023-01-28T13:06:07.151467 #759] FATAL -- :   
ActionView::Template::Error (undefined method `+' for nil:NilClass):
    36:             =svg_symbol '#icon-arrow-left', class: 'icon', title: 'Previous page'
    37: 
    38:           span.page-nav_info = t('.metadata')
    39:           -next_works = @collection.works.to_a[index+1..]
    40:           -next_work = next_works.detect {|candidate| candidate.pages.where(status: [nil, Page::STATUS_INCOMPLETE]).first || candidate.description_status == Work::DescriptionStatus::UNDESCRIBED }
    41:           -if next_work
    42:             -next_page = next_work.pages.where(status: [nil, Page::STATUS_INCOMPLETE]).first
  
app/views/shared/_description_tabs.html.slim:39
app/views/work/describe.html.slim:3
`

**Comment by benwbrum** [comment] 2023-03-27 13:04
Duplicate of #3575

**Comment by benwbrum** [comment] 2023-03-27 13:34
Duplicate of #3575

**Closed by benwbrum** 2023-03-27 13:34 UTC
Labels: servicability
