### ISSUE TITLE
Header getting buried under image in landscape view

### ISSUE THREAD

**Issue by anabeabas** [benwbrum/fromthepage#3441] opened 2022-12-20 15:42 UTC
Jodi of Digital Maryland emailed to inform us that the header gets lost underneath the image in landscape view. She says it does stay at the top, but she scrolls it under the image when she works since she uses the landscape view.

**Comment by sylvieed** [comment] 2023-01-02 22:41
Duplicate of #3002?

**Comment by benwbrum** [comment] 2024-04-15 15:34
Definitely a duplicate of #3002

**Closed by benwbrum** 2024-04-15 15:34 UTC
Labels: customer
