### ISSUE TITLE
"collaboration is restricted" for unrestricted works if not logged in

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#4020] opened 2024-04-04 19:08 UTC
> On the main page for London and Surrounding Area 2 works have 'Collaboration is restricted' when view as guest or not signed in after searching for project under Western University Archives.... I can't seem to see why this is displayed but other works on this page do not. These works were posted recently in February 2024.

If I'm not logged in to FromThePage, I see the "collaboration is restricted" status of 2 works here:
![image](https://github.com/benwbrum/fromthepage/assets/708566/a44ac759-9f30-453c-a15c-05a38375b633)
But if I click into them, they are not actually restricted -- I can transcribe them (even as a guest).

If I'm logged in they look fine:

![image](https://github.com/benwbrum/fromthepage/assets/708566/b1f3a851-56d2-42c8-b18e-7b624cde383a)

From UWO

**Comment by benwbrum** [comment] 2024-05-22 19:48
This may be a duplicate of #3950

**Comment by WillNigel23** [comment] 2024-05-29 18:23
I see we check for this to say it is not restricted
```
-if (current_user && current_user.can_transcribe?(work) && @collection.active?)
```

At the same time a collection has boolean field restricted.

I assume we should base it off of the boolean and that the above implementation is perhaps legacy? Can you confirm? @benwbrum @saracarl

**Comment by saracarl** [comment] 2024-05-29 18:39
A collection shouldn't have a restricted boolean -- only works are restricted.  But yes, we should base this message off of that boolean.  I think this does the right thing if a user is logged in, but if they aren't, `current_user.can_transcribe?(work)` must return false.

I think the logic should be this:

`(current_user && current_user.can_transcribe?(work) || work.unrestricted?) && @collection.active?`

Either you're logged in and can transcribe this work, or you aren't logged in and the work isn't restricted.  (and the collection is active)

**Comment by WillNigel23** [comment] 2024-05-29 18:59
Okay thanks for the clarification @saracarl ! I think I understand better now :smile:

**Closed** 2024-06-01 13:58 UTC
Labels: customer
