### ISSUE TITLE
500 Error on Start A Project

### ISSUE THREAD

**Issue by eturnator** [benwbrum/fromthepage#348] opened 2016-08-18 21:05 UTC
This is for the UT installation: Start A Project is giving a 500 error upon click.

**Comment by saracarl** [comment] 2016-10-02 22:26
We don't think this is happening anymore.  @atomrab -- is this still an issue?

**Comment by atomrab** [comment] 2016-10-03 14:51
@saracarl -- yes, this does seem to be an issue still. If I'm logged in and using the owner dashboard, I see two tabs: "Your works", with my documents, which is the default; and "Start a Project". If I click on the "Start a Project" tab, I get a page with the 500 message. The same happens if I click on the link to "Start a Project" that appears under each of the individual documents listed in "Your works".

**Comment by saracarl** [comment] 2016-10-13 13:54
@atomrab Just sent you and your team an email about a new version of FtP.  I'd like to test this issue against that code and if it still happens we will address it. I suspect it's caused by the "multiple owners" not being fully fleshed out, and @tbl73 is working another fix (not included in that release, unfortunately) around that that I have high hopes will finally put all of those related bugs to bed.

**Comment by atomrab** [comment] 2016-10-13 14:55
Perry just installed the new version (looks good!), and this is still happening.

**Comment by saracarl** [comment] 2016-10-13 15:00
Just looked at the logs, and this seems to be the problem:

I, [2016-10-13T09:49:55.840702 #29272]  INFO -- : Completed 500 Internal Server Error in 429ms
F, [2016-10-13T09:49:55.847039 #29272] FATAL -- : 
ActionView::Template::Error (undefined method `encoding' for nil:NilClass):
    33:       ul.omeka-sites
    34:         -@sc_collections.each do |sc_collection|
    35:           li.omeka-site
    36:             h5.omeka-site_title =link_to sc_collection.label, {:controller => 'sc_collections', :action => 'explore', :at_id => CGI::escape(sc_collection.at_id)}
    37:     =form_tag({ controller: 'sc_collections', action: 'explore_manifest' }) do |f|
    38:       table.form
    39:           td
  app/views/dashboard/startproject.html.slim:36:in `block in _app_views_dashboard_startproject_html_slim__1581545557777498371_62563380'
  app/views/dashboard/startproject.html.slim:34:in `_app_views_dashboard_startproject_html_slim__1581545557777498371_62563380'

We'll look into it.

**Comment by saracarl** [comment] 2016-10-13 15:12
We think this is a problem if you have never imported a IIIF collection (which UT hasn't/won't...).  We should be able to reproduce by using our old export of UT's database (which has no IIIF collections/works).

Relevant code:
dashboard_controller.rb line 47 & 48:
    @universe_collections = ScCollection.universe
    @sc_collections = ScCollection.all

startproject.html.slim around lines 34-36:

      ul.omeka-sites
        -@sc_collections.each do |sc_collection|
          li.omeka-site
            h5.omeka-site_title =link_to sc_collection.label, {:controller => 'sc_collections', :action => 'explore', :at_id => CGI::escape(sc_collection.at_id)}
    =form_tag({ controller: 'sc_collections', action: 'explore_manifest' }) do |f|


@tbl73 Can you try to reproduce this?  (Although I don't think you've ever imported IIIF on your test system?  Maybe you have a IIIF collection from a database I gave you??  I feel like we may be slightly off here.)

**Comment by tbl73** [comment] 2016-10-13 15:34
I'm not getting that error, but I'm pretty sure the database I'm using does have an IIIF collection, so that doesn't work.  I could use an old export of UT's database if you want to send it to me, or I could create a blank database and see if I can reproduce it that way.

**Comment by saracarl** [comment] 2016-10-14 13:18
We tried an older UT DB, but couldn't reproduce there either.  (Only 1 collection, so it's pretty early in UT's work with FtP.)  Sending email to Perry to see if we can get a more recent one.

**Comment by tbl73** [comment] 2016-10-14 18:28
I got the error to reproduce on the most recent db, so now I'm working on determining what's going on.

**Comment by tbl73** [comment] 2016-10-14 20:03
I found that there was some bad data in the sc_collections table on their database.  Once that data is removed, it seems to resolve the problem.  Pushed up a migration to remove that data in sccollection branch.

**Comment by tbl73** [comment] 2016-10-17 14:12
Resolved in pull request #446.

**Closed by tbl73** 2016-10-17 14:12 UTC
Labels: Needs Review
