### ISSUE TITLE
500 Server Error in "Pages that Need Review" Mode

### ISSUE THREAD

**Issue by jpa4ad** [benwbrum/fromthepage#633] opened 2017-04-19 15:22 UTC
I'm receiving a 500 Server Error using the "Pages that Need Review" option. The error occurs after I select that mode and then attempt to advance to the next set of pages marked as needing using the advance arrow review within a collection. Repeated to confirm issue.

**Comment by saracarl** [comment] 2017-04-19 16:12
Ok.  Thanks for reporting this.  I'm not sure we thought about advancing through a list of pages-for-review using the "next" button, so it could definitely cause problems.

I couldn't reproduce it on a simple try of "next" after being on a page that needed review.  I'm wondering if it happens when the pages needing review are non-contiguous (i.e. page 4 to page 6).  Could you give me the specific work and pages you were on?  

I'm going to go see if I can find the exact error in the logs as well.  

Thanks.

**Comment by saracarl** [comment] 2017-04-19 16:22
(And/or cut and paste a URL when you get the 500 error.)

**Comment by jpa4ad** [comment] 2017-04-19 16:25
No problem. Issue occurs in this collection:
https://www.fromthepage.com/display/read_work?work_id=719

When I went to this page:
https://www.fromthepage.com/display/read_work?needs_review=review&work_id=719

And upon clicking the arrow key I received server error via this URL:
https://www.fromthepage.com/display/read_work?page=2

**Comment by saracarl** [comment] 2017-04-19 16:33
From the log:

I, [2017-04-19T16:29:11.530061 #3811]  INFO -- : Started GET "/display/read_work?page=2" for 70.112.51.2
19 at 2017-04-19 16:29:11 +0000
I, [2017-04-19T16:29:11.531908 #3811]  INFO -- : Processing by DisplayController#read_work as HTML
I, [2017-04-19T16:29:11.531978 #3811]  INFO -- :   Parameters: {"page"=>"2"}
I, [2017-04-19T16:29:12.410262 #3811]  INFO -- : Completed 500 Internal Server Error in 878ms
F, [2017-04-19T16:29:12.412415 #3811] FATAL -- : 
NoMethodError (undefined method `pages' for nil:NilClass):
  app/controllers/display_controller.rb:14:in `read_work'

**Comment by tbl73** [comment] 2017-04-19 16:37
I can definitely replicate it by clicking the arrow at the bottom of the needs review pages list.  Oddly, if I go to the page using the link above (and click the arrow), it doesn't give me an error, but if you just click "Pages that need review" while in the work, and then try to use the arrow, it does.  I'm looking into it, but I wonder if going from the link might be a temporary workaround while I'm figuring it out?

**Comment by saracarl** [comment] 2017-04-20 17:33
Reviewed, merged, and deployed.  @jpa4ad -- would you try it again on fromthepage.com?  We believe that we've fixed it, but there's always a chance that we didn't understand all the nuances.  Thanks!

**Comment by jpa4ad** [comment] 2017-04-20 17:36
It is working on my end. Thanks!

**Closed** 2017-04-20 17:38 UTC
Labels: Needs Review
