### ISSUE TITLE
Some works imported from Archive.org do not display pages properly

### ISSUE THREAD

**Issue by benwbrum** [benwbrum/fromthepage#117] opened 2015-03-27 02:30 UTC
This is a problem reported by a site running the rails2 version of FromThePage--and which is ameliorated by the new Bookreader.js plugin, but still has problems.

The following works, when imported into FromThePage, do not display pages correctly due to problems in the URL Bookreader.js is requesting from the Internet Archive.
A catalogue of American seeds: https://archive.org/details/catalogueofameri1804mmah
Dreer's garden book: https://archive.org/details/dreersgardenbook1931dree
J.M. Thorburn & Co.'s annual descriptive catalogue of flower seeds: https://archive.org/details/jmthorburncosann1893thor
Barr & Sugden's spring seed catalogue: https://archive.org/details/barrsugdensspri1866barr_0

By contrast, these works seem to display properly.
May's catalogue of northern grown seeds, plants, bulbs & fruits (1920): https://archive.org/details/Mayquotscatalog00MayLB
Catalogo dei semi raccolti nell' anno …: https://archive.org/details/mobot31753004048952
Seeds for everybody at market gardener's prices: https://archive.org/details/Seedseverybodym00GlasB

To reproduce:
* Log in as a work owner 
* Owner Dashboard -> Actions
* Create an empty collection
* *create some test collection*
* Owner Dashboard -> Actions
* Import a Work from Archive.org
* Cut-and-paste one of the URLs above
* *Wait for the ingestion process to happen*
* Select the `Use OCR` checkbox
* Publish to FromThePage
* *Wait for the conversion process to finish*
* Collections -> *your test collection*
* Settings
* Add the imported work to the collection
* Now view a page of the work

**Comment by benwbrum** [comment] 2015-03-27 02:33
See screenshots for examples of the works which display properly and the ones which have bad scaling for an example.
![barr_and_sugden](https://cloud.githubusercontent.com/assets/199961/6861153/9a1b51f8-d3ff-11e4-8c21-2c3f076612cc.jpg)
![catalogo](https://cloud.githubusercontent.com/assets/199961/6861155/9a1d3c66-d3ff-11e4-9391-4c72ee817b04.jpg)
![catalogue_american_seeds](https://cloud.githubusercontent.com/assets/199961/6861156/9a1f9858-d3ff-11e4-936d-40dd53ac7a4a.jpg)
![dreer](https://cloud.githubusercontent.com/assets/199961/6861154/9a1d093a-d3ff-11e4-8d01-0d1a7b583d9b.jpg)
![mays](https://cloud.githubusercontent.com/assets/199961/6861158/9a2226a4-d3ff-11e4-85a8-8cbf8461004f.jpg)
![seeds_for_everybody](https://cloud.githubusercontent.com/assets/199961/6861157/9a20ab58-d3ff-11e4-8ff0-54c443417c9c.jpg)
![thorburn](https://cloud.githubusercontent.com/assets/199961/6861159/9a255b8a-d3ff-11e4-9eae-feba231df2ea.jpg)

**Comment by kolking** [comment] 2015-03-30 21:15
@benwbrum I've followed your instruction for the "Dreer's garden book", I see the same result as on your screenshots, all images are blurred. Started to investigate the nature of this bug, will keep you informed here in comments.

**Comment by benwbrum** [comment] 2015-03-30 21:34
I did a bit of research on this and found a problem with the `scale`
argument that the javascript was passing to the IA server via the page URL
method.  I'm afraid I can't be clearer than that.

Ben

**Comment by kolking** [comment] 2015-03-30 21:42
Yes, you're totally right, it is caused by the 'scale' argument. I was hoping that the problem at our side, but this 'scale' value is *somehow* calculated by the bookreader plugin. I'm trying to debug the plugin and find the place where it can set a wrong value.

**Comment by benwbrum** [comment] 2015-03-30 21:57
You may have found it already, but bookreader-devel@archive.org  has been
useful to me in the past.

**Comment by kolking** [comment] 2015-03-31 01:50
Well, it was our bug, let me explain. As we found before the 'scale' values were wrong, I thought that it could be a bookreader's bug, but it's not. It was caused by the wrong parsed image width and height values. Scandata XML file could contain several `<w>` and `<h>` elements for a `<page>`, here is the example:
```
<page leafNum="3">
<handSide>RIGHT</handSide>
<pageType>Title</pageType>
<addToAccessFormats>true</addToAccessFormats>
<rotateDegree>90</rotateDegree>
<origWidth>3744</origWidth>
<origHeight>5616</origHeight>
<ppi>500</ppi>
<cropBox>
<x>284</x>
<y>1225</y>
<w>2277</w>
<h>3850</h>
</cropBox>
<cropBoxAutoDetect>
<cropScore>5.85</cropScore>
<pass2Crop>
<x>136</x>
<y>944</y>
<w>2697</w>
<h>4393</h>
</pass2Crop>
<cleanCrop>
<l>136</l>
<r>2832</r>
<t>944</t>
<b>5336</b>
</cleanCrop>
<outerCrop>
<l>136</l>
<r>2832</r>
<t>944</t>
<b>5336</b>
</outerCrop>
<innerCrop>
<l>137</l>
<r>2831</r>
<t>945</t>
<b>5335</b>
</innerCrop>
<autoCropOptimized>
<x>252</x>
<y>1072</y>
<w>2532</w>
<h>4212</h>
</autoCropOptimized>
<minimized>
<x>504</x>
<y>1436</y>
<w>2276</w>
<h>3848</h>
</minimized>
<content>
<x>684</x>
<y>1944</y>
<w>2080</w>
<h>3268</h>
</content>
</cropBoxAutoDetect>
<skewAngle>0.30</skewAngle>
<skewAngleDetect>-1.23</skewAngleDetect>
<skewScore>3.43</skewScore>
<skewActive>true</skewActive>
</page>
```
Width and height were parsed with the following:
```
leaf.page_w = page.search('w').text
leaf.page_h = page.search('h').text
```
When there are many `<w>` elements, `page.search('w')` will return an array with all values found - `[2277,2697,2532,2276,2080]` and after converting this array to text we get `22772697253222762080` value for the page width.

I've fixed the Nokogiri search expressions, now it should work. Please note that after applying my fix you have to delete the imported works and re-import them again.

**Comment by benwbrum** [comment] 2015-03-31 01:52
Wow!

That's really impressive, Nick.

Thanks so much!

Ben

**Comment by kolking** [comment] 2015-03-31 02:02
I've also pushed the fix into master branch

**Closed** 2015-03-31 02:01 UTC
Labels: in progress

**Comment by saracarl** [comment] 2015-03-31 03:14
I've verified that this is fixed.
