### ISSUE TITLE
"Incomplete" checkbox

### ISSUE THREAD

**Issue by saracarl** [benwbrum/fromthepage#866] opened 2017-11-16 14:23 UTC
Can we spend some time designing / thinking about how much work it would be to add an "incomplete" checkbox to a page.  (That, not so hard...  what about statistics, though?  If marked "incomplete" then the page would count as "not transcribed")

@tbl73 can you think about this and document a bit, but not implement yet?

**Comment by benwbrum** [comment] 2019-07-19 16:54
New “incomplete” status and associated workflows
A new page status of "incomplete" will be added to the underlying data model; the percentage of pages
in this status will be reflected in the work listing displayed to transcribers and project owners. Users
will have a natural workflow based on save buttons on the transcription screen. 
Projects with open review/review to request help
For projects in which pages are not required to pass through a review stage, the following changes to
the user interface and workflow will be made:
1. When a user is transcribing an untouched page or a page that has been marked incomplete
(through this mechanism), instead of seeing only a "save" button they will see a "save" button
and a "save and mark complete" button. The later will be highlighted.
If the user presses the "save" button, their work will be saved, the page’s status will be marked
as "incomplete" and they will be returned to continue editing that page.
If the user presses the "save and mark complete" button, their work will be saved, the page
status will be marked complete and they will be directed to the next page needing transcribing.
2. If a page is marked "needs review" the user will see the "save" button and a "save and mark
reviewed" button. In this view, the "needs review" checkbox will be hidden.
Projects with required/defaulted review
For projects in which pages default to “needs review” on initial transcription, the following changes to
the user interface and workflows will be made:
1. When a user is transcribing an untouched or incomplete page, they will see “save” and “save
and mark for review” buttons. The “needs review” checkbox will not be visible.
Pressing “save” will mark the page status as “incomplete” and save their work. The user will
continue editing the page.
Pressing “save and mark for review” will save the user’s work and mark the page status as
“needs review”.
2. When a user edits a page marked as “needs review”, they will see “save” and “save and mark
reviewed” buttons.

Pressing “save” will keep the page status as “needs review”, save the user’s work, and allow
them to continue editing the page text.
Pressing “save and mark reviewed” will set the page status to a completed state and save the
user’s work.

**Comment by saracarl** [comment] 2019-09-23 18:49
See also email with design for OJA.

**Comment by mulcare** [comment] 2020-04-30 14:46
I want to give a more thorough +1 to this. The team of "owners" who have been managing the multi-collection Harvard Library account have all been looking for ways to handle tracking which works have been transcribed, which ones need another pass, and which ones are complete. 

The current system, which, as far as I understand it, essentially has 3 statuses--untranscribed, transcribed, needs review--is quite limiting. If unflagging "needs review" effectively just changes the status of a page to "transcribed", there's no obvious way to tell that a page is truly completed (since a half-transcribed page not flagged for review is _also_ "transcribed"). Having a more robust system of status marking [as Ben's laid out](https://github.com/benwbrum/fromthepage/issues/866#issuecomment-513300573) would make it much easier to understand what actions should/could be taken next on the page.

Ideally this extended status feature would come with extended role management as well. Having "editors" assigned on the collection level, who can "mark as reviewed" or "mark as complete, reviewed, and approved" would be helpful. Then collaborators can mark something as needing review when they believe it's reached completion, but authorized experts can make the final determination on whether it's completed. (This could be toggled per collection to not deal with it for those projects that want to maintain a more fully democratic crowdsourcing approach or don't have the resources to go through and "mark as reviewed," etc.)

**Comment by lenathelibrarian** [comment] 2020-05-15 13:56
I missed this discussion before, but I completely agree with @mulcare's comments

**Comment by saracarl** [comment] 2021-04-07 13:47
With the upcoming ledger/spreadsheet transcription, this is becoming even more important.

**Comment by benwbrum** [comment] 2021-04-28 13:55
This has been deployed; we now show two buttons, distinguishing between "Save" and "Finish" to allow users to save their work without marking it as completed.

**Closed by benwbrum** 2021-04-28 13:55 UTC
Labels: customer, ledger

**Comment by mulcare** [comment] 2021-04-30 01:18
@benwbrum, is this intended behavior? I just want to make sure I'm understanding the new button so I can effectively introduce a slightly new workflow for our collaborators

- If you check Needs Review and hit Save, your edits will indeed save, but the Needs Review state isn't saved (reverts back to unchecked on reload)
- If you check Needs Review and his Finish, edits are saved and Needs Review stays checked
- If you uncheck Needs Review and hit Save, Needs Review will no longer be checked, you'll no longer get the message about the work being marked as Needs Review, and _you will no longer have access tot he Finish button_

So, conceptually speaking, the sequence here goes:

```
IN PROGRESS                ->                                   FINISHED                 ->              "APPROVED/REVIEWED"
[edit, Save]        [Finish, Needs Review]          [Save, Needs Review toggleable]              [Save, Needs Review toggleable]
```

And a page could exist in one of 3 states:

1. IN PROGRESS, with edits being added
2. FINISHED + NEEDS REVIEW, with edits being possible but the page considered completed
3. FINISHED + APPROVED/REVIEWED, with edits still being possible, the page considered completed, and the page also being considered finalized/approved/reviewed

As I wrote this out, this does make sense to me, but I am interested in distinguishing between states 2 and 3; unless I'm just not seeing it, there's no indicator either on the page or in any deed log, that someone has come across a Needs Review finished item, reviewed and approved it, and then unchecked Needs Review. In other words, is there some was to see the status of pages that have been through all of those steps/states?

**Comment by saracarl** [comment] 2021-04-30 14:29
Hi @mulcare -- See if this helps:
https://content.fromthepage.com/save-vs-finish-button/

If we need to clarify anything, please let us know.  And if you find anything that seems not to be working logically, definitely let us know.  We'd be happy to chat about adding text to indicate page status when you're looking at it -- that sounds like a good idea since this has been a confusing change (and we didn't communicate clearly enough about it as we rolled it out).

**Comment by mulcare** [comment] 2021-04-30 16:53
Thanks, @saracarl. That writeup _is_ helpful, although I think it reveals where a key issue is: all of this seems to only apply to collections where "All initial transcriptions need review" is toggled on. It's somewhat confusing for collaborators, as that parameter isn't exposed to them (nor should it be), but the behavior of the interface is different depending on whether its toggled. For instance, there's no 'Approve' button at all, even when you manually toggle 'need review' on and click Finish, on pages within collections that don't have "All initial transcriptions need review" on.

Hopefully I'm making sense!

**Comment by saracarl** [comment] 2021-05-03 14:45
Hi @mulcare 

We did some testing, thinking and discussing and think this particular behavior:
`If you check Needs Review and hit Save, your edits will indeed save, but the Needs Review state isn't saved (reverts back to unchecked on reload)`
is wrong.  We should keep the "needs review" button checked.  (The assumption was that if it wasn't completely transcribed then someone would be reviewing it, but having a button unchecked right after you checked it is like slapping a transcriber on the hand for doing something the software told them to do -- bad form!) 
We're going to change this so if you check "needs review" and then "save" it will take you to the "needs review" state; the equivalent of checking "needs review" and then "finish".  (It's imperfect -- because you lost the fact that the page wasn't complete -- but the needs review will bring that page back into the "look at me" state and a reviewer can finish transcribing it...  Unfortunately this is the way it has to be with the states we have.)
